# Generated by Django 6.0 on 2025-12-16 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('tk', 'Türkmen')], default='ru', max_length=2, verbose_name='Язык'),
        ),
    ]
