# Generated by Django 5.1 on 2025-12-18 21:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_businessprofile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата регистрации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Заметки админа'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='subscription_end',
            field=models.DateField(blank=True, null=True, verbose_name='Подписка до'),
        ),
    ]
