# Generated by Django 6.0 on 2025-12-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_add_max_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Русский'), ('tk', 'Türkmen')], default='ru', max_length=2, verbose_name='Язык'),
        ),
    ]
