# Generated by Django 5.1 on 2025-12-23 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_businessprofile_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Время начала работы')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время конца работы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='crm.employee')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
    ]
