# Generated by Django 6.0 on 2025-12-24 10:44

import django.db.models.deletion
import secrets
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_worklog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('role', models.CharField(choices=[('manager', 'Менеджер'), ('specialist', 'Специалист'), ('admin', 'Администратор')], default='specialist', max_length=20, verbose_name='Должность')),
                ('token', models.CharField(default=secrets.token_urlsafe, max_length=100, unique=True, verbose_name='Токен приглашения')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата приглашения')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата принятия')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_invitations', to='crm.businessprofile')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('business', 'email')},
            },
        ),
    ]
